### ISSUE TITLE
bower is missing wrench dependency

### ISSUE THREAD

**Issue by edcoffin** [formio/formio-app-todo#3]
Error: Cannot find module 'wrench'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/eric/org/wge/code/form-portal/gulpfile.js:10:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by edcoffin** [comment]
Yikes - I had forgotten to run `npm install`
